name: Windows
on:
  push:
    paths:
      - "src/**"
      - "!**.md"
      - "!**.cmake"
      - ".github/workflows/windows.yml"
  pull_request:
    paths:
      - "src/**"
      - "!**.md"
      - "!**.cmake"
      - ".github/workflows/ubuntu.yml"  
  workflow_dispatch:
  
permissions: write-all

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        include:
          - qt_ver: 6.8.0
            qt_arch: win64_msvc2022_64
            msvc_arch: x64
    env: 
      targetName: sast-gallery.exe
      fileName: sast_gallery
      QT_MODULES: "qt5compat qtmultimedia"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: setup Ninja
        uses: ashutoshvarma/setup-ninja@v1.1
        with:
          version: "1.12.1"    

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_ver }}
          arch: ${{ matrix.qt_arch }}
          cache: ${{steps.cache-qt.outputs.cache-hit}}
          modules: ${{env.QT_MODULES}}
        
      - name: CMake Build
        id: build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.msvc_arch }}
          ninja --version
          cmake --preset native
          cmake --build --preset native-release
          echo winSdkDir=%WindowsSdkDir% >> %GITHUB_ENV%
          echo winSdkVer=%WindowsSdkVersion% >> %GITHUB_ENV%
          echo vcToolsInstallDir=%VCToolsInstallDir% >> %GITHUB_ENV%
          echo vcToolsRedistDir=%VCToolsRedistDir% >> %GITHUB_ENV%
    
      - name: package
        id: package      
        env:
          archiveName: ${{ env.fileName }}-${{ matrix.qt_arch }}
          msvcArch: ${{ matrix.msvc_arch }}
        shell: pwsh
        run: |
          & scripts\windows-publish.ps1 ${env:archiveName} ${env:targetName}
          $name = ${env:archiveName}
          echo "::set-output name=packageName::$name"

      - uses: actions/upload-artifact@v4
        if: startsWith(github.event.ref, 'refs/tags/')
        with:
          name: ${{ steps.package.outputs.packageName }}
          path: dist
            
      - name: inno setup install
        uses: zhuzichu520/inno-setup-action@v1.0.1
        with: 
          filepath: ./action-cli/InstallerScript.iss
          
      - name: upload release
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./action-cli/installer.exe
          asset_name: ${{ env.fileName }}_win32.exe
          tag: ${{ github.ref }}
          overwrite: true 